/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jp_co_nicovideo_eka2513_commentviewerj_plugin_AquesTalkPlugin */

#ifndef _Included_jp_co_nicovideo_eka2513_commentviewerj_plugin_AquesTalkPlugin
#define _Included_jp_co_nicovideo_eka2513_commentviewerj_plugin_AquesTalkPlugin
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jp_co_nicovideo_eka2513_commentviewerj_plugin_AquesTalkPlugin
 * Method:    speech
 * Signature: (Ljava/lang/String;ILjava/lang/String;)Z
 */
JNIEXPORT jint JNICALL Java_jp_co_nicovideo_eka2513_commentviewerj_plugin_AquesTalkPlugin_speech
  (JNIEnv *, jobject, jstring, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
